package com.example.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.staticCompositionLocalOf

enum class AppLanguage {
    GUJARATI,
    ENGLISH
}

object Strings {
    private val en = mapOf(
        "app_title" to "DWARKESH COCONUTS & NURSERY",
        "app_tagline" to "Quality Plants • Healthy Growth • Trusted Service",
        "hero_heading" to "Quality Coconut Plants for a Better Future",
        "hero_subheading" to "High-yielding, certified hybrid and dwarf coconut saplings for farmers & plantation enthusiasts across Gujarat.",
        "explore_plants" to "Explore Plants",
        "advance_booking" to "Advance Booking",
        "call_now" to "Call Now",
        "whatsapp" to "WhatsApp",
        "featured_plants" to "Featured Coconut Plants",
        "latest_plants" to "All Plants & Saplings",
        "special_offers" to "Special Seasonal Offers",
        "why_choose_us" to "Why Choose Dwarkesh?",
        "nursery_gallery" to "Nursery Gallery",
        "customer_reviews" to "Farmer & Customer Reviews",
        "how_to_book" to "How to Book Coconut Plants",
        "contact_us" to "Contact & Visit Us",
        "book_now" to "Book Now",
        "view_details" to "View Details",
        "price" to "Price",
        "stock" to "Stock",
        "available" to "Available",
        "out_of_stock" to "Out of Stock",
        "plant_age" to "Plant Age",
        "min_order" to "Min Order",
        "benefits" to "Key Benefits & Yield",
        "customer_name" to "Customer Name",
        "mobile_number" to "Mobile Number",
        "quantity" to "Plant Quantity",
        "delivery_type" to "Delivery Type",
        "nursery_pickup" to "Nursery Pickup",
        "home_delivery" to "Farm / Home Delivery",
        "address" to "Farm Address / Street",
        "village_city" to "Village / City",
        "district" to "District",
        "booking_date" to "Booking Date",
        "notes" to "Special Notes / Instructions",
        "total_amount" to "Total Amount",
        "advance_amount" to "Advance Amount Paid",
        "remaining_amount" to "Remaining Balance",
        "confirm_booking" to "CONFIRM ADVANCE BOOKING",
        "booking_receipt" to "Official Booking Receipt",
        "booking_id" to "Booking ID",
        "delivery_status" to "Delivery Status",
        "payment_status" to "Payment Status",
        "share_receipt" to "Share Receipt",
        "print_receipt" to "Print / Download PDF",
        "my_orders" to "My Bookings & Orders",
        "nav_home" to "Home",
        "nav_plants" to "Plants",
        "nav_bookings" to "My Orders",
        "nav_gallery" to "Gallery",
        "nav_admin" to "Admin",
        "nav_about" to "About Us",
        "nav_contact" to "Contact",
        "search_hint" to "Search coconut varieties, dwarfs, hybrids...",
        "all" to "All",
        "admin_panel" to "Dwarkesh Admin Panel",
        "admin_login" to "Secure Nursery Admin Login",
        "enter_pin" to "Enter 4-digit Security PIN",
        "unlock" to "Unlock Dashboard",
        "sign_out" to "Log Out",
        "save" to "Save Changes",
        "cancel" to "Cancel",
        "delete" to "Delete",
        "edit" to "Edit",
        "add_new_plant" to "Add New Plant",
        "price_management" to "Price & Discount Management",
        "booking_management" to "Booking Management",
        "media_management" to "Media & Image Management",
        "review_management" to "Customer Review Moderation",
        "contact_management" to "Nursery Contact Settings",
        "notifications" to "Notifications",
        "write_review" to "Submit Farmer Review",
        "signature_vansh_ram" to "Authorized Signature: Vansh Ram",
        "receipt_footer_msg" to "Thank you for choosing Dwarkesh Coconuts & Nursery",
        "copyright" to "© 2026 DWARKESH COCONUTS & NURSERY. All rights reserved."
    )

    private val gu = mapOf(
        "app_title" to "દ્વારકેશ કોકોનટ્સ & નર્સરી",
        "app_tagline" to "ઉત્તમ ગુણવત્તા • સ્વસ્થ વિકાસ • ભરોસાપાત્ર સેવા",
        "hero_heading" to "ગુણવત્તાયુક્ત નાળિયેરના રોપા માટે આજે જ સંપર્ક કરો",
        "hero_subheading" to "ખેડૂતો માટે વધુ ઉત્પાદન આપતા પ્રમાણિત હાઇબ્રિડ તેમજ વામન (ડ્વાર્ફ) નાળિયેરીના રોપા સમગ્ર ગુજરાતમાં ઉપલબ્ધ.",
        "explore_plants" to "રોપાઓ જુઓ",
        "advance_booking" to "એડવાન્સ બુકિંગ",
        "call_now" to "કોલ કરો",
        "whatsapp" to "વોટ્સએપ",
        "featured_plants" to "મુખ્ય નાળિયેરીના રોપાઓ",
        "latest_plants" to "તમામ નાળિયેર રોપા યાદી",
        "special_offers" to "ખાસ મોસમી ઓફર્સ",
        "why_choose_us" to "શા માટે દ્વારકેશ નર્સરી પસંદ કરવી?",
        "nursery_gallery" to "નર્સરી ગેલેરી",
        "customer_reviews" to "ખેડૂત મિત્રોના પ્રતિભાવો",
        "how_to_book" to "બુકિંગ કેવી રીતે કરવું?",
        "contact_us" to "સંપર્ક અને મુલાકાત",
        "book_now" to "બુક કરો",
        "view_details" to "વિગતો જુઓ",
        "price" to "ભાવ",
        "stock" to "સ્ટોક",
        "available" to "ઉપલબ્ધ છે",
        "out_of_stock" to "સ્ટોક ખાલી",
        "plant_age" to "રોપાની ઉંમર",
        "min_order" to "ઓછામાં ઓછો ઓર્ડર",
        "benefits" to "મુખ્ય ફાયદા અને ઉત્પાદન",
        "customer_name" to "ગ્રાહક / ખેડૂતનું નામ",
        "mobile_number" to "મોબાઇલ નંબર",
        "quantity" to "રોપાની સંખ્યા",
        "delivery_type" to "ડિલિવરી પ્રકાર",
        "nursery_pickup" to "નર્સરી પરથી મેળવવું",
        "home_delivery" to "વાડી / ખેતર સુધી ડિલિવરી",
        "address" to "સરનામું / વાડીનો વિસ્તાર",
        "village_city" to "ગામ / શહેર",
        "district" to "જિલ્લો",
        "booking_date" to "બુકિંગ તારીખ",
        "notes" to "ખાસ નોંધ / સૂચના",
        "total_amount" to "કુલ રકમ",
        "advance_amount" to "ચૂકવેલ એડવાન્સ રકમ",
        "remaining_amount" to "બાકી રહેતી રકમ",
        "confirm_booking" to "એડવાન્સ બુકિંગ કન્ફર્મ કરો",
        "booking_receipt" to "સત્તાવાર બુકિંગ પહોંચ",
        "booking_id" to "બુકિંગ આઈડી",
        "delivery_status" to "ડિલિવરી સ્થિતિ",
        "payment_status" to "પેમેન્ટ સ્થિતિ",
        "share_receipt" to "રસીદ શેર કરો",
        "print_receipt" to "પ્રિન્ટ / PDF ડાઉનલોડ",
        "my_orders" to "મારા ઓર્ડર્સ અને બુકિંગ",
        "nav_home" to "હોમ",
        "nav_plants" to "રોપાઓ",
        "nav_bookings" to "ઓર્ડર્સ",
        "nav_gallery" to "ગેલેરી",
        "nav_admin" to "એડમિન",
        "nav_about" to "અમારા વિશે",
        "nav_contact" to "સંપર્ક",
        "search_hint" to "વામન, હાઇબ્રિડ નાળિયેર રોપા શોધો...",
        "all" to "બધા",
        "admin_panel" to "દ્વારકેશ એડમિન પેનલ",
        "admin_login" to "સુરક્ષિત એડમિન લૉગિન",
        "enter_pin" to "૪ અંકનો સિક્યોરિટી PIN દાખલ કરો",
        "unlock" to "ડેશબોર્ડ ખોલો",
        "sign_out" to "લૉગ આઉટ",
        "save" to "ફેરફારો સેવ કરો",
        "cancel" to "રદ કરો",
        "delete" to "કાઢી નાખો",
        "edit" to "સુધારો",
        "add_new_plant" to "નવો રોપો ઉમેરો",
        "price_management" to "ભાવ અને ડિસ્કાઉન્ટ મેનેજમેન્ટ",
        "booking_management" to "બુકિંગ વ્યવસ્થાપન",
        "media_management" to "ફોટો અને મીડિયા મેનેજમેન્ટ",
        "review_management" to "ખેડૂત રિવ્યુ મંજૂરી",
        "contact_management" to "નર્સરી સંપર્ક નંબર સેટિંગ્સ",
        "notifications" to "સૂચનાઓ",
        "write_review" to "ખેડૂત પ્રતિભાવ આપો",
        "signature_vansh_ram" to "અધિકૃત સહી: વંશ રામ",
        "receipt_footer_msg" to "દ્વારકેશ કોકોનટ્સ & નર્સરી પર વિશ્વાસ મૂકવા બદલ આભાર",
        "copyright" to "© 2026 દ્વારકેશ કોકોનટ્સ & નર્સરી. સર્વાધિકાર સુરક્ષિત."
    )

    fun get(key: String, language: AppLanguage): String {
        return when (language) {
            AppLanguage.GUJARATI -> gu[key] ?: en[key] ?: key
            AppLanguage.ENGLISH -> en[key] ?: gu[key] ?: key
        }
    }
}

val LocalAppLanguage = staticCompositionLocalOf { AppLanguage.GUJARATI }

@Composable
fun AppText(key: String): String {
    val lang = LocalAppLanguage.current
    return Strings.get(key, lang)
}
